### PR TITLE
Fix blank bar at bottom of pfp

### PR DESCRIPTION
**Pull request by Ju1-js**

### CODE REVIEW

**Comment by splatboydev** [comment]
terrible code quality 💀💀

**Comment by Ju1-js** [comment]
Bro didn't even know about `aspect-ratio` 💀

**Comment by splatboydev** [comment]
no bitches?

**Comment by Ju1-js** [comment]
Bruh

**Comment by splatboydev** [comment]
nah I'll merge it because I'm cool

**Comment by splatboydev** [comment]
nvm

**Pull request closed without merging**
