### PR TITLE
Adhere to Community Standards

### PR DESCRIPTION
**Pull request by splatboydev**
This PR will add:
* A CoC
* Contributing guidelines
* Issue templates
* PR templates
* A security policy

@Ju1-js review this rn

### CODE REVIEW

**Comment by Ju1-js** [comment]
Bro turn this repo in to a discord server 💀 
Also,
image

**Comment by splatboydev** [comment]
for real

**Comment by splatboydev** [comment]
you didn't review it 💀

**Review by Ju1-js — COMMENTED** [review]
Nice CoC.

**Comment by splatboydev** [comment]
Indeed. re-star though <3

**Pull request merged**
